### ISSUE TITLE
how to prepare a pocket that is not the example in colab?

### ISSUE THREAD

**Issue by SanazKaz** [sekijima-lab/DiffInt#1]
Hello,

I am trying to use your colab notebook to generate some molecules for a given PDB ID. I added both sdf and pdb of this in place of example but i receive an error. I assume there must be some way i should prepare the pocket so it is within the 10Angstroms used in the paper. However, i cannot find example of how to do this

Please see the error.

Best wishes

#############################################################################################

IndexError                                Traceback (most recent call last)
[<ipython-input-15-70414a327dff>](https://localhost:8080/#) in <cell line: 2>()
      1 #@title Run Sampling
----> 2 out_sdf = ligand_generation(outdir='test_1', test_file=tmp2, checkpoint='checkpoints/best_model.ckpt', save=True)

2 frames
[/content/DiffInt/equivariant_diffusion/en_diffusion.py](https://localhost:8080/#) in <listcomp>(.0)
    997         c = n2 if n2 is not None else n1
    998 
--> 999         return torch.tensor([m[i].sample() for i in c], device=c.device)
   1000 
   1001     def log_prob(self, batch_n_nodes_1, batch_n_nodes_2):

IndexError: list index out of range

**Comment by msako82** [comment]
Thank you for your interest in our research.
If you are using data from the Protein Data Bank, please share the PDB ID you used.

The PDB file(1a2g_A_rec.pdb) used in the example was downloaded from the Protein Data Bank, with non-protein elements (water and ligand molecules) removed. You can construct PDB file using MDAnalysis, Biopython, or manually.
So, no distance cutoff is applied to this file.
For ligands, we are using downloaded files in SDF format from the Protein Data Bank.

You don't need to prepare the cut-out PDB file for the sample generation code in Colab because the process_data() function internally handles the data extraction.

**Comment by SanazKaz** [comment]
Many thanks for your response, this has solved my issue.
